name: Calling all other workflows from this
on:
  workflow_dispatch:
jobs:
  job1:
    uses: chaithragudimalla/Project_workflows/.github/workflows/pipelineconfig.yaml@main
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: powershell
        shell: pwsh
        run: | 
           if ({{ needs.job1.outputs.language }} == java && {{ needs.job1.outputs.build_tool }} == maven) {
              write-host " maven pipelinetype "
           } else {
              write-host " other "
           }
