name: Calling all other workflows from this
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  call_workflow:
        uses: chaithragudimalla/.github/workflows/pipelineconfig.yaml@main
        with:
          pipelineType: 'awsEBS'
          language: 'java'
          javaVersion: '11'
          slotting: 'abc'
          buildTool: 'maven'
          appName: 'abc-def'
          TargetFileType: 'war'
          ArchiveFilePath: './target'
