name: Calling all other workflows 
on:
  workflow_dispatch:
jobs:
  job1:
    uses: chaithragudimalla/Project_workflows/.github/workflows/pipelineconfig.yaml@main
  job2:
    needs: job1
    if: ${{ needs.job1.outputs.build_tool }} == 'nodejs'
    uses: chaithragudimalla/Project_workflows/.github/workflows/nodejs.yaml@main
    with:
       build_tool: nodejs
       versions: 14
  job3:
    needs: job1
    if: ${{ needs.job1.outputs.build_tool }} == 'maven'
    uses: chaithragudimalla/Project_workflows/.github/workflows/maven.yaml@main
    with:
       build_tool: maven
       versions: 14
  job4:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: getting values from pipelineconfig
        if: ${{ needs.job1.outputs.build_tool }} == 'maven'
        env:
           b: ${{ needs.job1.outputs.build_tool }}
        run: echo "$b"
  job5:
    runs-on: ubuntu-latest
    needs: job4
    steps:
       - name: checking
         env: 
            c: ${{ needs.job2.steps.env.b }}
         run: echo $c
