name: Calling all other workflows from this
on:
  workflow_dispatch:
jobs:
  job1:
    uses: chaithragudimalla/Project_workflows/.github/workflows/pipelineconfig.yaml@main
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: getting values from pipelineconfig
        if: ${{ needs.job1.outputs.build_tool }} == 'maven'
        env:
          b: ${{ needs.job1.outputs.build_tool }}
        run: echo "$b"
  job3:
    needs: job2
    uses: chaithragudimalla/Project_workflows/.github/workflows/${{ needs.job2.steps.env.b }}.yaml@main
    with:
       build_tool: maven
       versions: 14
  job4:
    runs-on: ubuntu-latest
    needs: job3
    steps:
       - name: checking
         shell: python
         run: b
