name: input file
on:
  workflow_call:
     inputs:
         pipelineType:
             type: string
             required: true
         language:
             type: string
             required: true
         javaVersion:
             type: string
             required: true
         slotting:
             type: string
             required: true
         buildTool:
             type: string
             required: true
         appName:
             type: string
             required: true
         TargetFileType:
             type: string
             required: true
         ArchiveFilePath:
             type: string
             required: true
