name: Reusable workflow

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      language:
        value: ${{ jobs.example_job.outputs.language }}
      build_tool:
        description: "The second output string"
        value: ${{ jobs.example_job.outputs.build_tool }}

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
       language: java
       build_tool: maven
