name: Reusable workflow

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      language:
        value: ${{ jobs.example_job.outputs.output1 }}
      build_tool:
        description: "The second output string"
        value: ${{ jobs.example_job.outputs.output2 }}

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.language }}
      output2: ${{ steps.step2.outputs.build_tool }}
    steps:
      - id: step1
        run: echo "::set-output name=language::'java'"
      - id: step2
        run: echo "::set-output name=build_tool::'maven'"
